#!/usr/bin/env bash

node_version='v0.11.12'

cd ~/open-source # where I clone git repos

if [ "$1" = 'u' ] ; then
    cd node
    git checkout master
    git pull -u origin master
    git checkout $node_version
    make clean
    make distclean
    ./configure --prefix=$HOME/local
    make install

    cd ../npm
    git pull
    make install # or `make link` for bleeding edge
else
    git clone git://github.com/joyent/node.git
    cd node
    git checkout $node_version
    ./configure --prefix=$HOME/local
    make install
    cd ..
 
    git clone git://github.com/isaacs/npm.git
    cd npm
    make install # or `make link` for bleeding edge
fi
