#!/usr/bin/env bash

cd ~/open-source/vim

hg pull && hg update

make clean
make distclean

./configure \
    --prefix=$HOME/local \
    --with-features=huge \
    --enable-pythoninterp \
    --enable-gui=gtk2
make
make install

echo 'Remember to add ~/local/bin to your $PATH'
