#!/usr/bin/env bash

# Find all dirs inside ./ and zip each of them into a separate file.

for f in *; do
    if [[ -d "$f" && ! -L "$f" ]]; then
        zip -r "${f}.zip" "$f"
        echo "Zipped ${f}.zip"
    fi
done
